# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: trtllm-gpt-oss-disagg
spec:
  services:
    Frontend:
      dynamoNamespace: trtllm-gpt-oss-disagg
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-gpt-oss:latest
    TRTLLMPrefillWorker:
      dynamoNamespace: trtllm-gpt-oss-disagg
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 1
      resources:
        limits:
          gpu: "4"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-gpt-oss:latest
          workingDir: /workspace/components/backends/trtllm
          command:
            - /bin/sh
            - -c
          args:
            - "python3 -m dynamo.trtllm --model-path /model --served-model-name openai/gpt-oss-120b --extra-engine-args engine_configs/gpt_oss/prefill.yaml --disaggregation-mode prefill --disaggregation-strategy prefill_first --max-num-tokens 20000 --max-batch-size 32 --free-gpu-memory-fraction 0.9 --tensor-parallel-size 4 --expert-parallel-size 4"
          volumeMounts:
            - name: model-storage
              mountPath: /model
        volumes:
          - name: model-storage
            hostPath:
              path: /data/models/gpt-oss-120b
              type: Directory
    TRTLLMDecodeWorker:
      dynamoNamespace: trtllm-gpt-oss-disagg
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 1
      resources:
        limits:
          gpu: "4"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-gpt-oss:latest
          workingDir: /workspace/components/backends/trtllm
          command:
            - /bin/sh
            - -c
          args:
            - "python3 -m dynamo.trtllm --model-path /model --served-model-name openai/gpt-oss-120b --extra-engine-args engine_configs/gpt_oss/decode.yaml --disaggregation-mode decode --disaggregation-strategy prefill_first --max-num-tokens 16384 --max-batch-size 128 --free-gpu-memory-fraction 0.9 --tensor-parallel-size 4 --expert-parallel-size 4"
          volumeMounts:
            - name: model-storage
              mountPath: /model
        volumes:
          - name: model-storage
            hostPath:
              path: /data/models/gpt-oss-120b
              type: Directory
